"""Deterministic audit summaries and explicitly judgmental forecast scenarios."""
from pathlib import Path
import collections,datetime,hashlib,json,math,statistics,zipfile
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'analysis/review-v1.5.0';STUDY=ROOT/'analysis/followup-v1.4.0/studies/mini-panel-20261008-v140'
def save(name,x):(OUT/name).write_text(json.dumps(x,indent=2)+'\n')
def bb(a,b):
 def beta(x,y):return math.lgamma(x)+math.lgamma(y)-math.lgamma(x+y)
 p=[math.comb(8,k)*math.exp(beta(a+k,b+8-k)-beta(a,b)) for k in range(9)]
 assert abs(sum(p)-1)<1e-12
 return p
def mixture(parts):
 p=[sum(w*bb(a,b)[k] for w,a,b in parts) for k in range(9)]
 return {'P_K_0_through_8':p,'expected_K':sum(k*v for k,v in enumerate(p)),'predicted_K_out_of_8':round(sum(k*v for k,v in enumerate(p))),'P_K_le_2':sum(p[:3])}
metrics=json.loads((OUT/'trajectory-metrics.json').read_text())['metrics'];inv=json.loads((OUT/'inventory.json').read_text());ex=json.loads((OUT/'exclusions.json').read_text())['attempts'];helper=json.loads((OUT/'helper-reconstruction/result.json').read_text());assert helper['replay_reward']==1
summary={};forecasts={}
for task in sorted({m['task'] for m in metrics}):
 rows=[m for m in metrics if m['task']==task];s=sum(m['finished_by_30_min'] for m in rows);signals=sum(m['finished_by_30_min'] or m['final_artifact_literal_written_by_30_min'] for m in rows)
 summary[task]={'label':'verified transcript timings; no 30-minute cutoff grading performed','passes':24,'valid_trials':24,'family_results':{model:{'passes':8,'valid_trials':8,'finished_trace_by_30_min':sum(m['finished_by_30_min'] for m in rows if m['model']==model)} for model in sorted({m['model'] for m in rows})},'median_agent_trace_minutes':statistics.median(m['agent_elapsed_seconds']/60 for m in rows),'min_agent_trace_minutes':min(m['agent_elapsed_seconds']/60 for m in rows),'max_agent_trace_minutes':max(m['agent_elapsed_seconds']/60 for m in rows),'finished_trace_by_30_min':s,'finished_or_literal_final_artifact_written_by_30_min':signals,'availability_signal_caveat':'A literal final-file write is positive evidence, not a graded snapshot of all dependencies at cutoff. Trace elapsed time omits some agent setup. Late completion does not prove a 30-minute failure.','unique_normalized_final_artifacts':len({m['normalized_artifact_sha256'] for m in rows})}
 forecasts[task]={'label':'inferred subjective forecast; target outcomes unknown; conditional on validity','confidence':'low','components':[{'weight':.6,'beta':[9,1],'interpretation':'Uniform-prior posterior for one proxy family at 8/8, used as a subjective ample-time predictor. Identical family posteriors are mixed, not multiplied.'},{'weight':.2,'beta':[1+s,25-s],'interpretation':'Pessimistic deadline scenario: count every trace finishing after 30 minutes as unsuccessful. Those are assumptions, not observed failures.'},{'weight':.2,'beta':[3,1],'interpretation':'Broad, uncalibrated scaffold/target discrepancy component. Parameters and weights are analyst choices after seeing this panel.'}],**mixture([(.6,9,1),(.2,1+s,25-s),(.2,3,1)]),'ample_time_sensitivity':mixture([(.8,9,1),(.2,3,1)]),'pessimistic_deadline_sensitivity':mixture([(.8,1+s,25-s),(.2,3,1)])}
ranking=sorted(forecasts,key=lambda t:forecasts[t]['P_K_le_2'],reverse=True)
records=[json.loads((ROOT/f).read_text()) for f in inv['per_trial_record'].values()];first=[r for r in records if r['phase']=='panel' and r['attempt']==1]
save('audit-summary.json',{'label':'verified offline audit; no inference calls','original_archive_sha256':inv['original_archive_sha256'],'original_frozen_package_files_unchanged':108,'successful_candidate_replays':120,'artifact_only_replays_passed':119,'trajectory_reconstructed_helper_replays_passed':1,'archive_dependency_gap_attempt':helper['attempt_id'],'unique_container_ids':120,'fresh_two_message_starts':120,'finished_traces_by_30_min':sum(m['finished_by_30_min'] for m in metrics),'per_task':summary,'excluded_status_counts':dict(collections.Counter(e['status'] for e in ex)),'first_attempt_status_counts':dict(collections.Counter(r['status'] for r in first)),'first_attempts':len(first),'protocol_failure_adjudication':'GLM emitted timeout_sec=620 when tool schema maximum was 600. This is a real model protocol error with a fail-fast harness response; keep separate from transport and task-semantic outcomes. Sensitivity: 120/121 if treated as an end-to-end unsuccessful model attempt; this is not the randomized primary-slot denominator.','uncertainty':'Conditioning on completed replacements may bias success upward. No frontier outcome or absence of contamination is established.'})
save('forecast-revision.json',{'version':'1.5.0','created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'post-development-panel revision, before any evaluator overnight or target results; original Day 1 freeze unchanged','targets_observed':False,'target_assumption':'Fable or GPT-5.6 Sol under the packaged 1800-second agent limit; actual evaluator scaffold and token allowance unknown. Neither target was run.','method':'Subjective mixture of beta-binomial eight-trial predictive distributions. No measured proxy-to-target transfer coefficient or strength bonus. Deadline scenario is intentionally adverse and not a 30-minute measurement.','ranking':ranking,'ranking_interpretation':'Mostly deadline sensitivity; all families pass every completed trial with ample time. No robust semantic difficulty ordering is demonstrated.','tasks':forecasts})
print(json.dumps({'ranking':ranking,'forecasts':{t:{k:forecasts[t][k] for k in ['predicted_K_out_of_8','expected_K','P_K_le_2']} for t in ranking},'first_attempts':collections.Counter(r['status'] for r in first)},indent=2))
